### ISSUE TITLE
WebOS 개발 환경 설정 ( 김진영 카톡 튜토리얼 참고 ) - 각자

### ISSUE THREAD

**Issue by Nyso00** [Queist/webos_object_detection#2]

**Comment by ddony8128** [comment]
https://webnautes.tistory.com/2010
VirtualBox에 캠 연결하는 방법

**Comment by Nyso00** [comment]
그거 이미 해봄

**Comment by ddony8128** [comment]
저대로 하면 webOS에서 노트북 웹캠이 제대로 작동하긴 함.
gst-launch-1.0 v4l2src ! videoconvert ! glimagesink 실행하면
ERROR: from element /GstPipeline:pipeline0/GstV4l2Src:v4l2src0: Internal data stream error.
라고 뜨는데 찾아보니까 파이프라인 설정하면서 뭔가 stream 사이즈라던가 더 고쳐줘야 하는 거 같은데 아직 잘 모르겠음.

**Comment by ddony8128** [comment]
참고로 웹캠이 버박과 제대로 연결 안 되어 있을 땐

ERROR: from element /GstPipeline:pipeline0/GstV4l2Src:v4l2src0: Cannot identify device '/dev/video0'.
Additional debug info:
../gst-plugins-good-1.20.7/sys/v4l2/v4l2_calls.c(608): gst_v4l2_open (): /GstPipeline:pipeline0/GstV4l2Src:v4l2src0:
system error: No such file or directory

이렇게 뜸. 리눅스 상에서 캠에 /dev/video0 가 연결되어 있나봄
